data_name: task6

camera:
    camera: 'zed_mini'
    camera_fps: 60
    camera_resolution: VGA #VGA-672,376
    depth_mode: ULTRA #PERFORMANCE
    depth_max: 16000
    depth_min: 100
    vicon : True
    
animation:
    fps: 20

preprocess:
    skip_frame: NotImplemented
    image_size: [376,672]
    resize_shape: [256, 256] 
    image_min_dim: 672
    image_max_dim: 672

robot:
    acceleration: 0.3 #0.9
    velocity: 0.5

segment:
    batch_size: 8
    learning_rate: 0.00001

pose: 
    batch_size : 8
    scale : 0.5
    supervision : 'never' #'never' #'full' #'both_ends'
    learning_rate: 0.00001 

discriminator:
    learning_rate: 0.0001

object:
    nb_object: 1
