task_name: task1

camera:
    camera: 'zed'
    camera_fps: 60
    camera_resolution: VGA #VGA-672,376
    depth_mode: ULTRA #PERFORMANCE
    depth_max: 16000
    depth_min: 100
    image_size : [720, 1280]
    
animation:
    fps: 20

preprocess:
    skip_frame: NotImplemented
    image_size: [270, 480]
    scale : 0.375
    
segment:
    batch_size: 1
    learning_rate: 0.00001

pose: 
    batch_size : 1
    scale : 0.375
    learning_rate: 0.00001 






robot:
    acceleration: 0.3 #0.9
    velocity: 0.5



discriminator:
    learning_rate: 0.0001

object:
    nb_object: 1
